In [2]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [7]:
boston = datasets.load_boston()
X = boston.data
y = boston.target
X = X[y<50]
y = y[y<50]
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [8]:
lin_reg = LinearRegression()
lin_reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [9]:
lin_reg.score(X_test,y_test)

0.7406757807474562

In [10]:
lin_reg.coef_

array([-1.00861836e-01,  3.19099585e-02, -5.28924623e-02,  2.48916630e-01,
       -1.25309448e+01,  3.54177951e+00, -2.46929830e-02, -1.19625565e+00,
        2.96016759e-01, -1.52806978e-02, -9.26178164e-01,  7.23839598e-03,
       -3.64249159e-01])

In [11]:
lin_reg.intercept_

36.0144336569294

In [14]:
sort = np.argsort(lin_reg.coef_)
sort

array([ 4,  7, 10, 12,  0,  2,  6,  9, 11,  1,  3,  8,  5], dtype=int64)

In [18]:
np.argsort(np.array([0,10,2,5,8,7]))

array([0, 2, 3, 5, 4, 1], dtype=int64)

In [23]:
boston.feature_names[sort[len(sort)-5:]]

array(['B', 'ZN', 'CHAS', 'RAD', 'RM'], dtype='<U7')